requirements: upgrade invenio-theme to 2.5.2
* Pin Flask-Menu<1.0.0, since new release v1.0.0 gives:
  AttributeError: 'Menu' object has no attribute 'submenu'