datacite: account for absence of data abstract or table description
* The previous commit gave "UndefinedError: 'None' has no attribute 'decode'" for records where the data abstract or table description is missing.

Signed-off-by: Graeme Watt <graeme.watt@durham.ac.uk>