requirements: bump invenio-logging to 4.2.0
* invenio-logging 4.0.2 installs sentry-sdk 1.45.1.  With Python 3.14:
  TypeError: cannot pickle 'FrameLocalsProxy' object
* Also upgrade beautifulsoup4 and xmlschema as bumped by Dependabot.