elasticsearch: fix exception searching if any table DOIs are None
* Fixes "AttributeError: 'NoneType' object has no attribute 'split'".
* It shouldn't happen that a 'doi' is None, but avoid breaking search.