elasticsearch: sort tables in search results by table ID not table name
* Previous code (from 2015) sorted by a digit in table name ("Table 1"),
  or by the table name otherwise. Mixed cases give a Python 3 exception:
  TypeError: '<' not supported between instances of 'int' and 'str'
* Could sort by 'recid' of table, but it doesn't match order of tables.
* The 'id' of a table reflects the order of tables, but need to use DB.
* Not ideal to access the DB from elasticsearch module, but it works.
* Need to add 'version' to search_test.py and omit DB access for test.